name: Custom Pipeline

on:
  push:
    branches-ignore:
      - main
      - develop
      - release/**

  pull_request:
    branches:
      - main
      - develop
      - release/**

  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/products-app:${{ github.sha }}

jobs:

