name: Custom Pipeline

on:
  push:
    branches-ignore:
      - main
      - develop
      - release/**

  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ env.PROJECT_NAME }}-app:${{ github.sha }}

jobs:

