name: Custom Pipeline

on:
  push:
    branches:
      - main
      - develop

  pull_request:

  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/products-app:${{ github.sha }}

jobs:
