name: Custom Pipeline

on:
  pull_request:
    branches:
      - main
      - develop
      - release/**

  workflow_dispatch:

env:
  PROJECT_NAME: users
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/users-app:${{ github.sha }}

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME ./projects/$PROJECT_NAME

      - name: Push image to GitHub Container Registry
        run: docker push $IMAGE_NAME

  test:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: docker pull $IMAGE_NAME

      - name: Run unit tests
        run: docker run --rm --entrypoint "" $IMAGE_NAME sh -c "npm run migrate && npm run seed && npm test"

      - name: Run e2e tests
        run: docker run --rm --entrypoint "" $IMAGE_NAME sh -c "npm run migrate && npm run seed && npm run test:e2e"

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push, test]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: docker pull $IMAGE_NAME

      - name: Simulate deploy
        run: |
          echo "🚀 Simulando deploy em produção..."
          docker run -d -p 3000:3000 $IMAGE_NAME
          echo "✅ Aplicação em execução em http://localhost:3000"
